/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.samplejavafx.base;


import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        final Label message = new Label("Hello, JavaFX!");
        StackPane root = new StackPane(message);
        stage.setTitle("Hello World!");
        stage.setScene(new Scene(root, 300, 200));
        stage.show();
    }

    public static void run(String[] args) {
        launch(args);
    }
}